### ISSUE TITLE
Error when calling api from angular

### ISSUE THREAD

**Issue by Jonasdero** [SWE-V-Modell/vmodell-server#1]
> Access to XMLHttpRequest at 'http://localhost:1382/api/modul' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Vielleicht ein Cors Paket installieren oder cors requests freischalten
Keine ahnung wo ich das machen muss
ist auf jeden fall server side

**Comment by lhfwc** [comment]
Error happened due to an overlap of requests on a single database connection. Issue was resolved by creating a connection-pool.
